spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
      show-sql: true
    open-in-view: false
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    username: sa
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
oauth2:
  provider:
    google:
      client-id: { googleClientId }
      client-secret: { googleClientSecret }
      redirect-uri: { googleRedirectUri }
      token-uri: https://oauth2.googleapis.com/token
      user-info: https://www.googleapis.com/oauth2/v2/userinfo
    kakao:
      client-id: { kakaoClientId }
      client-secret: { kakaoClientSecret }
      redirect-uri: { kakaoRedirectUri }
      token-uri: https://kauth.kakao.com/oauth/token
      user-info: https://kapi.kakao.com/v2/user/me

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
